name: M174_kayak
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - blas=1.0=mkl
  - boto3=1.40.54=py311haa95532_0
  - botocore=1.40.54=py311haa95532_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - click=8.2.1=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h9214b88_0
  - geographiclib=2.1=py311haa95532_0
  - geopy=2.4.1=py311haa95532_0
  - greenlet=3.2.4=py311h885b0b7_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jmespath=1.0.1=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_core=5.8.1=py311haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libkrb5=1.21.3=h885b0b7_4
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - narwhals=2.7.0=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.4=py311h050da96_1
  - numpy-base=2.3.4=py311h1e017a8_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h42c1672_1
  - parso=0.8.5=py311haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py311haa95532_0
  - plotly=6.3.0=py311hbc747e5_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - psycopg2=2.9.10=py311h827c3e9_0
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-dotenv=1.1.0=py311haa95532_0
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pyzmq=27.1.0=py311h7149c55_1
  - referencing=0.37.0=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - s3transfer=0.14.0=py311haa95532_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlalchemy=2.0.43=py311hda9a48d_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - idna==3.11
      - meteofrance-api==1.4.0
      - requests==2.32.5
prefix: C:\Users\maria\.conda\envs\M174_kayak
